---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/bram2000/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Code/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignoreglobal
  - .osx
  - .vimrc
  - .zshrc
  - .globalrc

homebrew_installed_packages:
  - neovim
  - asdf
  - fish
  - autoconf
  - zsh
  - zsh-syntax-highlighting
  - z
  - git
  - tig
  - hub
  - go
  - gpg
  - httpie
  - libevent
  - nmap
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - ripgrep
  - ag
  - pyenv
  - pyenv-virtualenv
  - pipenv
  - rbenv
  - fswatch
  - entr
  - links
  - ctop
  - telnet
  - awscli
  - aws-shell
  - pstree
  - unrar
  - fzy
  - bat
  - fd
  - tree
  - tidy-html5
  - mas
  - youtube-dl
  - axel
  - fzf
  - jmespath/jmespath/jp
  - jq
  - yq
  - yamllint
  - jid
  - global
  - ffmpeg
  - libav
  - coreutils
  - tldr
  - findutils
  - csvkit
  - libpq
  - grc
  - docker-completion
  - speedread
  - speedtest-cli
  - dark-mode
  - pandoc
  - pandoc-citeproc
  - pandoc-crossref
  - pandoc-include-code
  - plantuml
  - gdal
  - heroku

homebrew_taps:
  - homebrew/core
  - homebrew/cask-fonts
  - jmespath/jmespath
  - bram2000/homebrew-custom
  - heroku/brew


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - aerial
  - docker
  - firefox
  - google-chrome
  - licecap
  - slack
  - transmit
  - iterm2
  - launchbar
  - little-snitch
  - spectacle
  - dash
  - tunnelblick
  - keybase
  - spotify
  - evernote
  - visual-studio-code
  - postman
  - font-fantasque-sans-mono-nerd-font
  - font-fira-code
  - vlc
  - macpass
  - dropbox
  - github
  - virtualbox
  - virtualbox-extension-pack
  - istat-menus
  - meld
  - steam
  - xld
  - gimp
  - audio-hijack
  - keycastr
  - drawio
  - hazeover
  - vcv-rack
  - ableton-live-suite
  - beardedspice
  - vanilla
  - fantastical
  - macdown
  - surge-synthesizer
  - basictex
  - sonic-visualiser
  - discord
  - qgis

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 494803304, name: "WiFi Explorer (2.4)" }
  - { id: 1054607607, name: "Helium (2.0)" }
  - { id: 425424353, name: "The Unarchiver (3.11.5)" }
  - { id: 406056744, name: "Evernote (7.1)" }
  - { id: 671736912, name: "FruitJuice (2.3.3)" }
  - { id: 568494494, name: "Pocket (1.7.5)" }
  - { id: 412754595, name: "SoundCloud (1.3.2)" }
  - { id: 411643860, name: "DaisyDisk (4.5)" }
  - { id: 552383089, name: "Dashlane (5.10.0)" }
  - { id: 972028355, name: "Micro Snitch (4.2)" }
    #mas_signin_dialog: yes
mas_upgrade_all_apps: yes
mas_email: "bram2000@me.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: 
    - eslint-cli
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
    - mdv
    - Pygments
    - ipython
    - flake8
    - yapf
    - autoflake
    - isort
    - aws-fuzzy-finder
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
