---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/bram2000/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Code/dotfiles
dotfiles_files:
  - .gitconfig
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - zsh
    #- doxygen
    #- gettext
    #- gifsicle
  - git
  - go
  - gpg
    #- hub
  - httpie
    #- iperf
  - libevent
    #- sqlite
    #- mcrypt
  - nmap
    #- node
  - nvm
    #- php
  - ssh-copy-id
    #- cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - ag

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - blue-jeans
  - docker
  - firefox
  - google-chrome
  - licecap
  - slack
  - transmit
  - iterm2
  - launchbar
  - little-snitch
  - micro-snitch
  - spectacle
  - dash3
  - tunnelblick

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 494803304, name: "WiFi Explorer (2.4)" }
  - { id: 1054607607, name: "Helium (2.0)" }
  - { id: 425424353, name: "The Unarchiver (3.11.5)" }
  - { id: 406056744, name: "Evernote (7.1)" }
  - { id: 671736912, name: "FruitJuice (2.3.3)" }
  - { id: 568494494, name: "Pocket (1.7.5)" }
  - { id: 412754595, name: "SoundCloud (1.3.2)" }
  - { id: 411643860, name: "DaisyDisk (4.5)" }
  - { id: 972028355, name: "Micro Snitch (1.2)" }
  - { id: 552383089, name: "Dashlane (5.10.0)" }
    #mas_signin_dialog: yes
mas_upgrade_all_apps: yes
mas_email: "bram2000@me.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
