let g:python_host_prog = "/Users/" . $USER . "/.venv/neovim2/bin/python"
let g:python3_host_prog = "/Users/" . $USER . "/.venv/neovim3/bin/python"

let $NVIM_TUI_ENABLE_TRUE_COLOR=1
set termguicolors

" Some plugins don't play nicely with fish shell
set shell=/bin/bash

" Plugins
call plug#begin('~/.vim/plugged')
    Plug 'tpope/vim-rhubarb'
    Plug 'tpope/vim-surround'
    Plug 'tpope/vim-dispatch'
    Plug 'tpope/vim-unimpaired'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-repeat'
    Plug 'tpope/vim-vinegar'
    Plug 'tpope/vim-sensible'
    Plug 'tpope/vim-abolish'
    Plug 'tpope/vim-commentary'
    Plug 'tommcdo/vim-fugitive-blame-ext'
    Plug 'morhetz/gruvbox'
    Plug 'justinmk/molokai'
    Plug 'joshdick/onedark.vim'
    Plug 'KeitaNakamura/neodark.vim'
    Plug 'rakr/vim-one'
    Plug 'BrainDeath0/Hypsteria'
    Plug 'vim-scripts/Gummybears'
    Plug 'haishanh/night-owl.vim'
    Plug 'godlygeek/tabular'
    Plug 'plasticboy/vim-markdown'
    " Plug 'suan/vim-instant-markdown'
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'airblade/vim-gitgutter'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'neoclide/coc.nvim', { 'branch': 'release' }
    Plug 'bogado/file-line'
    Plug 'machakann/vim-highlightedyank'
    Plug 'sheerun/vim-polyglot'
    Plug 'majutsushi/tagbar'
    Plug 'Yggdroot/indentLine'
    Plug 'SirVer/ultisnips'
    Plug 'honza/vim-snippets'
    " Plug 'w0rp/ale'
    Plug 'chrisbra/csv.vim'
    Plug 'reinh/vim-makegreen'
    Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }
    Plug 'darfink/vim-plist'
    " Plug 'ryanoasis/vim-devicons'
    Plug 'moll/vim-bbye'
    Plug 'mileszs/ack.vim'
    Plug 'vim-pandoc/vim-pandoc'
    Plug 'vim-pandoc/vim-pandoc-syntax'
    Plug 'rizzatti/dash.vim'
    Plug 'glench/vim-jinja2-syntax'
    Plug 'NLKNguyen/papercolor-theme'
    Plug 'vim-test/vim-test'
call plug#end()

" Coc extensions
let g:coc_global_extensions = [
    \ 'coc-yaml',
    \ 'coc-stylelintplus',
    \ 'coc-html',
    \ 'coc-fzf-preview',
    \ 'coc-eslint',
    \ 'coc-tsserver',
    \ 'coc-styled-components',
    \ 'coc-pyright',
    \ 'coc-json',
    \ 'coc-go',
    \ 'coc-docker',
    \ 'coc-css'
\ ]

" Appearance
set background=dark
" colorscheme gruvbox
colorscheme PaperColor

" let g:airline_theme='gruvbox'
let g:airline_theme='papercolor'
set relativenumber
set number
set showtabline=2
set noshowmode


" Behaviour
set nofoldenable
set backupcopy=yes  " prevents entr running twice on vim save
set inccommand=nosplit
set expandtab
set tabstop=4
set shiftwidth=4
set smartindent
set mouse=nv
set cursorcolumn
set cursorline
set hidden
set clipboard=unnamedplus
if executable('rg')
    set grepprg='rg\ --vimgrep'
    let g:ackprg = 'rg --vimgrep'
endif
set completeopt=longest,menuone
set sessionoptions+=globals

" let <Enter> accpet a match in completion menu
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
inoremap <expr> <C-n> pumvisible() ? '<C-n>' :
  \ '<C-n><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'
inoremap <expr> <M-,> pumvisible() ? '<C-n>' :
  \ '<C-x><C-o><C-n><C-p><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'

" Map F1 to Esc in insert and allow it to quit help
inoremap <F1> <Esc>
noremap <F1> :call MapF1()<CR>
function! MapF1()
  if &buftype == "help"
    exec 'quit'
  else
    exec 'help'
  endif
endfunction

function! FormatPythonDictAsJson() range
  execute a:firstline . "," . a:lastline . "s/'/\"/g"
  execute a:firstline . "," . a:lastline . 's/None/"None"/g'
  execute a:firstline . "," . a:lastline . 's/True/true/g'
  execute a:firstline . "," . a:lastline . 's/False/false/g'
  execute a:firstline . "," . a:lastline . '!python -m json.tool'
endfunction
command! -range FormatPythonDictAsJson <line1>,<line2>call FormatPythonDictAsJson()


function! IwhiteToggle()
    if &diffopt =~ 'iwhite'
        set diffopt-=iwhite
    else
        set diffopt+=iwhite
    endif
endfunction

" Use `:Format` to format current buffer
command! -nargs=0 Format :call CocAction('format')

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Mappings
noremap <F2> :TagbarToggle<CR>
noremap <F4> :CocCommand<CR>
noremap <F5> :diffupdate<CR>

" Ctrl-Space to open completion list
inoremap <silent><expr> <c-space> coc#refresh()

map sq :Bdelete<CR>
noremap <Leader>q :Bwipeout<CR>
map <Leader><Enter> :Buffers<CR>
nmap <silent> <Leader>d <Plug>(coc-definition)
nmap <silent> <Leader>r <Plug>(coc-references)
nmap <silent> <leader>rn <Plug>(coc-rename)
noremap <Leader>c :Gvdiff<CR>
noremap <Leader>g :CocCommand fzf-preview.GitFiles<CR>
noremap <Leader>f :CocCommand fzf-preview.ProjectFiles<CR>
noremap <Leader>t :Tags<CR>
noremap <Leader>b :CocCommand fzf-preview.Buffers<CR>
noremap <Leader>o <ESC>:only<CR>
noremap <Leader>m <ESC>:exec &mouse!=""? "set mouse=" : "set mouse=nv"<CR>
xmap <Leader>l <Plug>(coc-format-selected)
" noremap <Leader>l :ALEFix<CR>
nnoremap <Leader>l :Format<CR>
noremap <Leader>e :Explore<CR>
" noremap <Leader>s :Sexplore<CR>
noremap <Leader>s :CocCommand python.sortImports<CR>
noremap <Leader>r :CocCommand fzf-preview.CocReferences<CR>
noremap <Leader>w :call IwhiteToggle()<CR>
nnoremap <silent> <Leader>ag :Ack <C-R><C-W><CR>
nnoremap <silent> <Leader>gs :Gstatus<CR>:20wincmd_<CR>
" nmap <silent> <leader>d <Plug>DashSearch

nmap <Leader>1 <Plug>lightline#bufferline#go(1)
nmap <Leader>2 <Plug>lightline#bufferline#go(2)
nmap <Leader>3 <Plug>lightline#bufferline#go(3)
nmap <Leader>4 <Plug>lightline#bufferline#go(4)
nmap <Leader>5 <Plug>lightline#bufferline#go(5)
nmap <Leader>6 <Plug>lightline#bufferline#go(6)
nmap <Leader>7 <Plug>lightline#bufferline#go(7)
nmap <Leader>8 <Plug>lightline#bufferline#go(8)
nmap <Leader>9 <Plug>lightline#bufferline#go(9)
nmap <Leader>0 <Plug>lightline#bufferline#go(10)

" Netrw
let g:netrw_liststyle = 3
let g:netrw_fastbrowse = 0
autocmd FileType netrw setl bufhidden=wipe

" Tagbar
let g:tagbar_zoomwidth = 0

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
let g:airline_powerline_fonts = 1
let g:airline#extensions#coc#enabled = 1

autocmd FileType json syntax match Comment +\/\/.\+$+
autocmd BufRead,BufNewFile *.htm,*.html setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Ultisnips
" Trigger configuration. Do not use <tab> if you use
" https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger='<tab>'

" shortcut to go to next position
" let g:UltiSnipsJumpForwardTrigger='<c-j>'

" shortcut to go to previous position
" let g:UltiSnipsJumpBackwardTrigger='<c-k>'

let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

" Markdown
let g:vim_markdown_conceal = 0
let g:vim_markdown_folding_disabled = 1
let g:instant_markdown_autostart = 0
let g:indentLine_fileTypeExclude = ['markdown']

" FZF preview options
let g:fzf_preview_filelist_command = 'rg --files --hidden --follow --no-messages -g \!"* *"'
let g:fzf_preview_command = 'ccat --color=always {-1}'
let g:fzf_preview_if_binary_command = "string match 'binary' (file --mime {})"
let g:fzf_preview_filelist_postprocess_command = 'gxargs -d "\n" exa --color=always'

" Pandoc
let g:pandoc#biblio#sources="bgy"
let g:pandoc#command#latex_engine="pdflatex"
let g:pandoc#syntax#conceal#use = 0

" vim-test
let test#strategy = "neovim"
let g:test#python#pytest#options = '-vv -s'

" Move to last cursor position on file open (:help restore-cursor)
autocmd BufReadPost *
  \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
  \ |   exe "normal! g`\""
  \ | endif

" Automatically switch the background colour when dark-mode is toggled
function! SetBackgroundMode(...)
    let s:dark_mode = systemlist("dark-mode status")[0]
    if s:dark_mode ==? "on"
        let s:new_bg = "dark"
    else
        let s:new_bg = "light"
    endif
    if &background !=? s:new_bg
        let &background = s:new_bg
    endif
endfunction
call SetBackgroundMode()
call timer_start(10000, "SetBackgroundMode", {"repeat": -1})
